version: '3'

services:
  node0:
    container_name: gurunode0
    image: "gurufin/guru"
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./build/node0/gurud:/guru:Z
    command:
      - /gurud start --home /guru
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: gurunode1
    image: "gurufin/guru"
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - ./build/node1/gurud:/guru:Z
    command:
      - /gurud start --home /guru
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: gurunode2
    image: "gurufin/guru"
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build/node2/gurud:/guru:Z
    command:
      - /gurud start --home /guru
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: gurunode3
    image: "gurufin/guru"
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build/node3/gurud:/guru:Z
    command:
      - /gurud start --home /guru
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.10.0/24